# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Setup Node
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: npm install sfdx-cli --global

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
        USERNAME: rishu24r_1@gmail.com
        INSTANCE_URL: https://login.salesforce.com
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a prod

    # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    - name: Run Validation on Deploy Source
      run: sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u prod -w 10
    
    # Deploy
    - name : Deploy to SF Org
      run: sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u prod -w 10
